### ISSUE TITLE
friendly ranges?

### ISSUE THREAD

**Issue by masterkain** [rbgdevx/healer-in-range#1]
I'm about to test out the addon and the weakaura but it was my understanding that blizzard restricted friendly range checks while in combat.

how does this works?

**Comment by rbgdevx** [comment]
hey thanks so much for taking the time to comment and checkout the addon! sorry for such a late response @masterkain, that is correct in PVE instances but not for PVP which admittedly has been the focus of all my addons - specifically RBG's.

**Comment by rbgdevx** [comment]
if you ever have any more questions or suggestions feel free to message me directly on discord @ajaex
